# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - azwebappserv

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://azwebappdemo.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3e068dbaaaf144a9987111dde14ae47e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_065781ff4cd5414b93eeca79bba08cda }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: azwebappdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3e068dbaaaf144a9987111dde14ae47e }}/containerdemos:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'azwebappserv'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_eecef818586b420584e2cc5ab922cf88 }}
        images: 'azwebappdemo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3e068dbaaaf144a9987111dde14ae47e }}/containerdemos:${{ github.sha }}'